In [19]:
import numpy as np


In [ ]:

def permU(U):

    return U


In [27]:
def compact_SVD(U):

    v,s,w = np.linalg.svd(U)
    cutDim = len(s[np.where(s==0)])
    if cutDim !=0 :
        v = v[:, :-cutDim]
        s = s[:-cutDim]
        w = w[:-cutDim, :]

    return v, s, w


[1 2 3 7 5 5 0]
1
[1 2 3 7 5 5]
[[0 1]
 [1 0]]
0


(array([[ 0., -1.],
        [-1.,  0.]]),
 array([1., 1.]),
 array([[-1., -0.],
        [-0., -1.]]))

In [ ]:
def reshapeVW(V, W):

    r = len(V[0,:])
    V = V.reshape(2,2,r)
    W = W.reshape(r,2,2)
    
    return V, W

In [ ]:
def reshapeVW(V, W):

    return V, W

    
def decompose(fSim: np.array):
    fSim = permU(fSim)
    v,s,w = compact_SVD(fSim)
    v, w = reshapeVW(v, w)
    return v, s, w