In [2]:
import numpy as np

In [13]:
def reorder_gate(G, perm):
    """
    Adapt gate ’G’ to an ordering of the qubits as specified in ’perm’.
    Example, given G = np.kron(np.kron(A, B), C):
    reorder_gate(G, [1, 2, 0]) == np.kron(np.kron(B, C), A)
    """
    perm = list(perm)
    # number of qubits
    n = len(perm)
    # reorder both input and output dimensions
    perm2 = perm + [n + i for i in perm]
    return np.reshape(np.transpose(np.reshape(G, 2*n*[2]), perm2), (2**n, 2**n))

(array([[1., 0.],
        [0., 1.]]),
 matrix([[ 0.70710678,  0.70710678],
         [ 0.70710678, -0.70710678]]),
 matrix([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]]),
 matrix([[1.        +0.j        , 0.        +0.j        ,
          0.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 1.        +0.j        ,
          0.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.        +0.j        ,
          1.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.        +0.j        ,
          0.        +0.j        , 0.70710678+0.70710678j]]))

In [36]:
I = np.eye(2)
H = 1/np.sqrt(2) * np.array([[1,1], [1, -1]])
CS = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1j]])
CT = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, np.exp(np.pi*1j/4)]])
expected = np.array([[np.exp(2*np.pi*1j*j*k/8)/np.sqrt(8) for j in range(8)] for k in range(8)])

I, H, CS, CT

(array([[1., 0.],
        [0., 1.]]),
 array([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]]),
 array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]]),
 array([[1.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ],
        [0.        +0.j        , 1.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ],
        [0.        +0.j        , 0.        +0.j        ,
         1.        +0.j        , 0.        +0.j        ],
        [0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.70710678+0.70710678j]]))

In [47]:
step1 = np.kron(H, np.kron(I, I))
step2 = reorder_gate(np.kron(CS, I) * reorder_gate(step1, [1,0,2]), [1,0,2])
step3 = reorder_gate(np.kron(CT, I) * reorder_gate(step2, [2,0,1]), [1,2,0])
step4 = np.kron(I, np.kron(H, I)) * step3
step5 = reorder_gate(np.kron(CS, I) * reorder_gate(step4, [2,1,0]), [2,1,0])
step6 = np.kron(I, np.kron(I, H)) * step5
final = reorder_gate(step6, [2,1,0])

error = abs(sum(sum(final - expected)))
error


3.266737344087186