In [1]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import axes3d

x_dim = 50
y_dim = 50

In [2]:
def load_np(name):
	B_load = np.load(name)
	B = np.zeros((x_dim, y_dim, 3))

	for i in range(x_dim):
		for j in range(y_dim):
			for k in range(3):
				B[i,j,k] = B_load[(i*x_dim + j)*3 + k]
	return B


In [3]:
# Load data
B = load_np('processed_data/B_Lorentzian.npy')
B_rough = np.load('processed_data/B_rough.npy')

B_mag = load_np('processed_data/B_mag_Lorentzian.npy')
B_mag_rough = np.load('processed_data/B_mag_rough.npy')


In [6]:
import plotly.graph_objs as go
import numpy as np 

B_x = B[:,:,0]
B_y = B[:,:,1]
B_z = B[:,:,2]

print(B_x)

x_points = []
y_points = []
z_points = []

for i in range(x_dim):
	for j in range(y_dim):
		x_points.append(np.array(i+0, i+B_x[i][j]))
		y_points.append(np.array(j+0, j+B_y[i][j]))
		z_points.append(np.array(0, B_z[i][j]))

fig = go.Figure(data=go.Scatter3d(x=x_points, y=y_points,z=z_points, mode='lines'))
fig.show() 

[[0.17137329 0.17254752 0.17196828 ... 0.1706914  0.17209914 0.17075302]
 [0.17251967 0.17337689 0.17341834 ... 0.17140894 0.17075141 0.17082216]
 [0.17571795 0.17474814 0.17273748 ... 0.17216672 0.17216368 0.17223075]
 ...
 [0.17120838 0.17257141 0.17254844 ... 0.17072429 0.17074624 0.17071053]
 [0.17263831 0.17259915 0.17258629 ... 0.17075841 0.17074934 0.17079578]
 [0.17267324 0.173972   0.17259032 ... 0.172776   0.17070405 0.1707315 ]]
